version: '3'

services:

  nginx-1.21:
    image: nginx:1.21
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ./src/pizza:/var/www/pizza
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/ssl/certs:/etc/ssl/certs
      - ./nginx/etc/ssl/private:/etc/ssl/private
      - ./nginx/usr/local/share/ca-certificates:/usr/local/share/ca-certificates
    depends_on:
      - php-7.4.30-fpm
      - mysql-8.0

  mysql-8.0:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: 127.0.0.1

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  php-7.4.30-fpm:
    build:
      context: php-fpm
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "7.4.30"
        PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
    container_name: php-fpm
    volumes:
      - ./src/pizza:/var/www/pizza
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${PHP_PORT}:9000"
    

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   ports:
  #       - '8888:80'
  #   environment:
  #       - PMA_ARBITRARY=1
  #       - PMA_HOST=mysql
  #   depends_on:
  #       - mysql-8.0
  #   env_file:
  #       - .env
